### ISSUE TITLE
How can I install Pytorch?

### ISSUE THREAD

**Issue by enesgur** [pyston/pyston_v2#105]
Hello,

I’m using Pyston for the AI scripts, but I've got some errors during the install Pytorch 1.8.0 package. 

The error is “wheel is not supported on this platform”. I upgraded the wheel and pip but I failed.

I am using Debian 10 amd64 architecture. Pyston is 2.3.1.

**Comment by undingen** [comment]
Unfortunately there are no prebuild packages for pyston available yet which makes installing much harder.
You will have to follow their guide on installing it from source for now: https://github.com/pytorch/pytorch#from-source

**Comment by enesgur** [comment]
I see. Thanks for your reply.

**Comment by makslevental** [comment]
@undingen i'm comfortable compiling pytorch from source so i'd like to experiment with this. problem is i have no idea what this actually entails, i.e., do i just compile using your llvm dep? i'm imagining it must be something else along the lines of `-fc++-abi=...`?

**Comment by kmod** [comment]
It depends on how pytorch is configured -- but most projects automatically configure themselves to build against the Python interpreter that you use to run the build process, so it hopefully is as simple as saying `pyston setup.py install`

**Comment by makslevental** [comment]
@kmod thanks for the quick response. will report back on results :)

**Comment by undingen** [comment]
Also we do have a [precompiled pytorch](https://anaconda.org/pyston/pytorch/files) if you can use conda.
More infos about how to use conda with pyston: https://github.com/pyston/pyston/wiki/Using-conda

**Comment by makslevental** [comment]
@undingen interesting. so do you see perf improvements? the last blog post i read (not sure from when) said that you operate pytorch in fallback mode and therefore there's no perf improvement

**Comment by undingen** [comment]
We have not tested how the performance compares but it should be at least as fast as using PyTorch with CPython - there is no fallback/compatibility overhead. But we can only speedup Python code so if all of the pytorch code is running inside C/GPU etc Pyston will not speed it up.
Would be really interested in hearing what performance you are seeing if you end up experimenting with pyston.
