### ISSUE TITLE
Pyston Docker image cant install Numpy

### ISSUE THREAD

**Issue by LiorA1** [pyston/pyston_v2#112]
Hi, 
I trying to install Numpy on Pyston docker image and its keeps failing..

(Even after upgrade pip)

I think that it is because of the os (alpine ?), but I'm not sure.

Is it possible to install Numpy on using Pyston ?

**Comment by undingen** [comment]
The following instructions work for me:
```
$ docker run -it --rm pyston/pyston /bin/bash
root@f118a7c76dcd:/# apt-get update
root@f118a7c76dcd:/# apt-get install build-essential
root@f118a7c76dcd:/# pip install numpy
```
I think you are likely missing the build essentials (gcc and co) which are required because numpy must be build from source when using pyston.

**Comment by LiorA1** [comment]
It worked. Thanks !
(Will try to do some basic benchmarks)

btw, Pyston can run on alpine/slim images ?

**Comment by undingen** [comment]
I have not tried but I assume our portable release (pyston_2.3.1_portable_v2.tar.gz) will work on alpine linux.
Looking forward to your feedback :).

**Comment by LiorA1** [comment]
Thanks for the help !
