### ISSUE TITLE
Tox testing implementation

### ISSUE THREAD

**Issue by ozkansen** [pyston/pyston_v2#151]
Hi,

How to pyston is tox integration ?

**Comment by kmod** [comment]
We'd love to integrate with tox! I haven't looked at it but my guess is this would have to happen in the tox project, not here? If you have any idea on how to do the integration just let us know!

**Comment by ozkansen** [comment]
İ have no idea :)

ok i write tox project, thank you

**Comment by undingen** [comment]
I actually did start on adding Pyston support to Tox.
Here is my very very work in progress change https://github.com/undingen/tox/tree/pyston
I'm currently on holiday and don't really know what the latest state is / what problems it currently has I just read you issue and thought I would upload it. Unfortunately I don't know Tox so some of the changes may be wrong.

----
Tox issue: https://github.com/tox-dev/tox/discussions/2292
