### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by JohnMoutafis** [pyston/pyston_v2#156]
Hello, we are using pyston in a project and suddenly yesterday it started failing builds.
Some side packages (which were pinned for a couple of months now) failed with the following error:

> lib/zoneinfo_module.c:1:10: fatal error: Python.h: No such file or directory
      1 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
> ERROR: Failed building wheel for backports.zoneinfo
> Failed to build backports.zoneinfo
> ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects

- The packages are: `pyxdameraulevenshtein` and `backports.zoneinfo`
- Pyston version: `2.2` and `2.3.1` `portable` and `system` install in ubuntu 20.04
- Tried upgrading `pip` with no effect.
- Tried with `python3.8` and the packages were installed without any issue.

**Comment by undingen** [comment]
I think this is this the same issue: https://github.com/pyston/pyston/issues/152
A new setuptools 60 got released which is unfortunately not compatible with Pyston currently. As a workaround you can set an environment flag `export SETUPTOOLS_USE_DISTUTILS=stdlib` to get old behavior back.
We working on a more permanent solution. 

Can you please try if this fixes your issue?

**Comment by JohnMoutafis** [comment]
@undingen Yes that worked! 
Thank you for the workaround.

We will be obliged if you let us know when this issue is resolved :)

**Comment by kmod** [comment]
Closing since this is the same issue as #152

We've incorporated this workaround into the [2.3.2 release](https://github.com/pyston/pyston/releases/tag/pyston_2.3.2) we just posted
