### ISSUE TITLE
I got this error after trying to install from docker and it seems that no binary file created with the name pyston3

### ISSUE THREAD

**Issue by Mng-dev-ai** [pyston/pyston_v2#18]
![image](https://user-images.githubusercontent.com/50384638/117300544-f20ac500-ae79-11eb-85c6-56860a54acad.png)

**Comment by kmod** [comment]
Thanks for the report!  Looks like we didn't realize you need to initialize the macrobenchmarks submodule in order to build Pyston (I just added it to the build instructions), could you try doing `git submodule update --init pyston/macrobenchmarks` and seeing if if works after that?

**Comment by Mng-dev-ai** [comment]
Thank you! I tried it but it returns git@github.com: Permission denied (publickey).

**Comment by kmod** [comment]
Ah sorry about that, just pushed a fix. Could you try pulling and trying again? Depending on your repo state there's a chance you might have to run `git submodule sync` for my change to take effect.

**Comment by Mng-dev-ai** [comment]
Sorry for being late, it's working, thank you
