### ISSUE TITLE
Compilation Error on `pyston_master` branch (GNU/Linux, gcc 8.3.0, python 3.7.3)

### ISSUE THREAD

**Issue by chocorho** [pyston/pyston_v2#22]
I attempted to compile the code on the `pyston_master` branch, installed dependencies, ran `../configure --enable-optimizations` and then ran `make`, and got the following compilation error:

```
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DENABLE_AOT   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fprofile-generate -I../Include/internal -IObjects -IInclude -IPython -I. -I../Include   -I../../aot  -DPy_BUILD_CORE -o Python/import.o ../Python/import.c
../Python/import.c: In function ‘_PyImport_Fini2’:
../Python/import.c:300:5: error: implicit declaration of function ‘_PyMem_SetDefaultAllocator’; did you mean ‘_PyMem_SetupAllocators’? [-Werror=implicit-function-declaration]
     _PyMem_SetDefaultAllocator(PYMEM_DOMAIN_RAW, &old_alloc);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
     _PyMem_SetupAllocators
cc1: some warnings being treated as errors
```

When I try using the latest release, I get the same exact error.

I currently have Python 3.7.3 installed; do I simply need to install python 3.8?

**Comment by undingen** [comment]
Sorry that this is a bit unclear but please don't run cpythons configure manually. We have to pass some special flags to it.
Instead just run `make` in the top directory and it will run configure for you (it actually has to configure two different cpythons etc).

**Comment by chocorho** [comment]
Thanks very much-! A plain old `make` invocation did progress beyond the previous error. However, now I'm getting a new error with the following:
```
/tmp/tmp_env/bin/python3 pyston/run_profile_task.py
Traceback (most recent call last):
  File "pyston/run_profile_task.py", line 13, in <module>
    run("macrobenchmarks/benchmarks/djangocms.py", "800") # approx 21s
  File "pyston/run_profile_task.py", line 8, in run
    subprocess.check_call(["/usr/bin/time", exe, bench] + list(args))
  File "/home/chozorho/git/pyston/pyston/build/cpython_opt_install/usr/lib/pyston3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/chozorho/git/pyston/pyston/build/cpython_opt_install/usr/lib/pyston3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/chozorho/git/pyston/pyston/build/cpython_opt_install/usr/lib/pyston3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/chozorho/git/pyston/pyston/build/cpython_opt_install/usr/lib/pyston3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/time'
make: *** [Makefile:190: pyston/build/cpython_opt_install/usr/bin/python3.bolt.fdata] Error 1
```

I know that `time` is a command I can invoke (I use it from the terminal every once in a while to measure command runtimes). But if I type `locate time`, nothing comes up, so I have no idea where this utility is installed, but it's definitely not in `/usr/bin`.

@undingen Do you have any advice for me? And if not, is it worth opening a new Issue for it?

**Comment by undingen** [comment]
We forgot to mention one must `apt-get install time` (I fixed the readme). Some of our benchmark scripts use `/usr/bin/time` instead of the shells build in `time` to get more verbose output.
