### ISSUE TITLE
Source Release tarball

### ISSUE THREAD

**Issue by BtbN** [pyston/pyston_v2#23]
Would it be possible to add a source tarball to the 2.2 release which includes all the submodules?
The current one is not very useful, since the build fails early due to all the missing submodules.

**Comment by chocorho** [comment]
This is a good idea, but simply out of curiosity, is your build error the same one that I encountered (#22)? I just want to make sure I'm not alone.

**Comment by BtbN** [comment]
It doesn't even get that far. It just fails almost instantly, because it tries to run cmake on a sub-project that doesn't exist.

**Comment by kmod** [comment]
That shouldn't be too hard, but out of curiosity is there a reason you don't want to clone the repository?

**Comment by BtbN** [comment]
It's for an ebuild and other packaging environments. Having an all-in-one tarball avoids having an otherwise needles dependency on git.
Cloning all those submodules also takes a considerable amount of time and extra space, even in shallow mode.

**Comment by kmod** [comment]
Ok I uploaded a source archive as part of the release: https://github.com/pyston/pyston/releases/download/pyston_2.2/pyston_2.2_src.tar.gz
