### ISSUE TITLE
2.3.4 release

### ISSUE THREAD

**Issue by kmod** [pyston/pyston_v2#246]
- [x] x86 debs + portable release @kmod 
- [x] x86 conda packages
- [x] x86 conda installer @undingen 
- [x] x86 docker images (blocked on debs) @kmod
- [x] arm debs + portable release @kmod
- [x] arm conda packages
- [x] arm conda installer @undingen 
- [x] arm docker images (blocked on debs) @kmod
- [x] x86-linux pyston-lite
- [x] arm-linux pyston-lite
- [x] x86 conda pyston-lite
- [x] x86-mac pyston-lite @undingen
- [x] arm-mac pyston-lite @undingen

**Comment by kmod** [comment]
@undingen would you mind looking into the conda installers? I created the x86 one successfully but I saw that it pulled in a 2.3.3 package and I didn't have time to investigate further

I think we have plenty of time so there's no need to work on it over the weekend

**Comment by undingen** [comment]
I will look into it

**Comment by undingen** [comment]
https://github.com/pyston/pyston/pull/248 fixes the installer issue

**Comment by stuaxo** [comment]
Are the docker images unblocked ?   From a naive reading of this list looks like everything is unblocked ?

**Comment by undingen** [comment]
I think we just forgot to mark them as done. @kmod will know it.

**Comment by kmod** [comment]
ah yeah I think I just forgot to cross these off and close the issue
