### ISSUE TITLE
Support 32-bit OSes and CPUs

### ISSUE THREAD

**Issue by KOLANICH** [pyston/pyston_v2#251]

**Comment by undingen** [comment]
Unfortunately we totally lack 32bit support currently :disappointed:  and it would be a lot of work to add some things which I think cause problem:
- JIT compiler needs to use different calling convention
- has only half the number of registers available on x86
- I think aarch32 instruction set is very different from aarch64 so would be like supporting a new architecture
- we make some assumptions about some fields size being 64bit (e.g. reference count field for immortal objects)

**Comment by KOLANICH** [comment]
Thank you for documenting the obstacles.

**Comment by kmod** [comment]
This is a valid request, but with our limited resources I don't think we're ever going to implement it.
