### ISSUE TITLE
pyston-lite-autoload is missing a wheel

### ISSUE THREAD

**Issue by gruebel** [pyston/pyston_v2#254]
Hi,

thanks for the great new way of leveraging Pyston optimization via the new packages `pyston-lite` and `pyston-lite-autoload` 🚀 

When I tried to install the `autoload` package in a fresh `venv` it will result in following error
```shell
pip install pyston-lite-autoload==2.3.4.1
Collecting pyston-lite-autoload==2.3.4.1
  Downloading pyston_lite_autoload-2.3.4.1.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... done
Collecting pyston_lite==2.3.4.1
  Downloading pyston_lite-2.3.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (466 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.1/466.1 KB 7.0 MB/s eta 0:00:00
Using legacy 'setup.py install' for pyston-lite-autoload, since package 'wheel' is not installed.
Installing collected packages: pyston_lite, pyston-lite-autoload
  Running setup.py install for pyston-lite-autoload ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyston-lite-autoload did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: option --single-version-externally-managed not recognized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyston-lite-autoload
```
it looks like this package has no wheel uploaded to `pypi`. I tried to figure out, how you create and upload the package, but couldn't find the script for it.

**Comment by undingen** [comment]
Can you please try `pip install wheel` before running `pip install pyston-lite-autoload`.
I'm not sure why this is required but I think it will fix your issue.

**Comment by gruebel** [comment]
@undingen forgot to write this, yeah it fixes the problem, but it would be nice, if it is not needed to install `pyston-lite-autoload` 🙂

**Comment by kmod** [comment]
Thanks for the report! I just wrote #255 which will upload a wheel for the autoload package as well, and I uploaded an autoload wheel for the latest release (2.3.4.2). Could you try it out and let me know if it works for you now?

**Comment by gruebel** [comment]
@kmod thanks, that worked 🚀 an other question, but kind of related. Would it be possible to also release a 2.3.4.2 version for the two Mac flavours? Somehow `pipenv` can't handle that `autoload` has the 2.3.4.2 version, but `pyston-lite` doesn't have the same version for Mac.
```shell
Warning: pyston-lite-autoload==2.3.4.2; python_version == '3.8' and (sys_platform == 'linux' or sys_platform == 'darwin') doesn't match your environment, its dependencies won't be resolved.
Could not find a version of pyston-lite; python_version == '3.8' and (sys_platform == 'linux' or sys_platform == 'darwin') that matches your environment, it will be skipped.
```

**Comment by undingen** [comment]
I'm going to build the missing mac and arm packages.

**Comment by kmod** [comment]
The packages have been uploaded!
