### ISSUE TITLE
Version mismatch on pip install pyston_lite_autoload -Windows Server 2016 Azure VM

### ISSUE THREAD

**Issue by funkybunchofoats** [pyston/pyston_v2#265]
Issue:
Trying to install pyston-lite-autoload from pypi fails with an error message

Output:
Collecting pyston_lite_autoload
  Using cached pyston_lite_autoload-2.3.4.2-py3-none-any.whl (1.4 kB)
  Using cached pyston_lite_autoload-2.3.4.1-py3-none-any.whl (1.4 kB)
ERROR: Cannot install pyston-lite-autoload==2.3.4.1 and pyston-lite-autoload==2.3.4.2 because these package versions have conflicting dependencies.
The conflict is caused by:
    pyston-lite-autoload 2.3.4.2 depends on pyston-lite==2.3.4.2
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    pyston-lite-autoload 2.3.4.1 depends on pyston-lite==2.3.4.1
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Trying to install pyston-lite first results in a package not found error message.

**Comment by funkybunchofoats** [comment]
nvm, I see there's an open issue/enhancement about bringing to windows.  I didn't see it on the blog or the pypi page or pyston.org so I hadn't anticipated it didn't have a build for windows yet.

**Comment by undingen** [comment]
yes, unfortunately we don't support Windows at the moment. 
Pyston-lite works on Linux and MacOS (while "full" Pyston only works on Linux).

You could try running it in WSL2.

**Comment by WoolenWang** [comment]
> 

when do we support windows?

**Comment by kmod** [comment]
We'd like to do it but unfortunately due to time constraints this isn't something we've put on our 6-month roadmap. We'd very much welcome contributions though!

**Comment by kmod** [comment]
We changed how we packaged things a bit so you should at least get a better error message here, something like "no available distribution for pyston_lite_autoload" (let me know if that's not the case). I'm going to close this as completed, though of course the windows support isn't done, but I think that belongs in a separate issue.
