### ISSUE TITLE
Which branch is stable?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [pyston/pyston_v2#281]
Hi there, I'm looking to build from source on Ubuntu 22.04. Which branch should I use if I want the latest stable release (what you package as tar.gz)?

I also don't see which version corresponds to which Python version.

**Comment by kmod** [comment]
We're using the `pyston_main` branch, which is what you should get when you clone the repo. Pyston-full only targets Python 3.8 so there's not a choice in that; pyston-lite (which it sounds like you're not talking about) has all versions supported in the same code, and will build for the version of Python that you use to run setup.py.

**Comment by kmod** [comment]
I'm going to close this but please feel free to reopen if there are further issues!
