### ISSUE TITLE
Why we use helper functions rather than use assembly to write all opcodes

### ISSUE THREAD

**Issue by JasonChen233** [pyston/pyston_v2#285]
In my view, using helper functions is more easier to write some long and complex opcode，but adding an extra function call will cause some performance lost. 

Can we use some tools like [compiler explorer](https://godbolt.org/) to translate the helper function to assembly and emit them by dynasm for opcodes？Maybe it can improve the performance ?

**Comment by kmod** [comment]
We're definitely open to this idea -- Marius has in the past migrated some things from helper functions to direct assembly. In my personal experience I don't tend to see the helper functions show up in the performance profiles and I believe we only use helper functions for opcodes that are quite infrequent. I guess I'm trying to say that I definitely agree with you in theory that this can be helpful, but Marius has already taken a crack at this so my initial thought is that any remaining gains are potentially insignificant, and come with downsides that need to be considered.

In particular it's not necessarily a performance improvement -- this is a form of inlining, which is not always beneficial. In particular for large and infrequent opcodes, including them in the assembly stream would increase the code size which is bad for cache performance, and potentially without meaningful benefits. Again, we're still open to there being room for improvement, just trying to say that this is something that's already been worked on so my initial reaction is that it's probably in a good state.

**Comment by JasonChen233** [comment]
I see! Inlining these opcodes does improve performance in small benchmark, but in test case which is close to a real project，inlining these  ops cause more i-cache miss(from be profiled from perf tool), and finally lead to performance lost.

So I agree that helper functions are better for theres  opcodes, thanks for your explanation.

**Comment by kmod** [comment]
I'm going to close this but please feel free to reopen if there are further issues!
