### ISSUE TITLE
Can you explain how you made `pyston` faster than  `CPython`

### ISSUE THREAD

**Issue by scharf** [pyston/pyston_v2#29]
I would like to understand how you made `pyston` faster than `CPython`.  Just a few sentences would help to evaluate if I want to use it for my project.

What are you reusing of CPython and what have you changed?

**Comment by kmod** [comment]
We started with their code and changed things, so most of what we have is unmodified from CPython. The bulk of our speedups come from JIT'ing hot functions to avoid interpreter overhead, and aggressive attribute-lookup caching. We also have a number of small optimizations throughout the CPython codebase.
