### ISSUE TITLE
This is an optimization bug?

### ISSUE THREAD

**Issue by zzl261004** [pyston/pyston_v2#311]
test.py
```
def test():
    a = [1, 2, 3]
    exhit = iter(a)
    for i in exhit:
        pass
    a.append("this should'be in exhit")
    print(f"got {list(exhit)}, should be []")

for i in range(6):
    test()
```

Behavior on pyston:
```
got [], should be []
got [], should be []
got [], should be []
got [], should be []
got [], should be []
got ["this should'be in exhit"], should be []
```
The output of the last line is wrong.It's a JIT optimization problem?
Test Environment:
Pyston:Python 3.8.12 (remotes/origin/release_2.3.5:4b858b5062, Sep 25 2022, 18:56:33) [Pyston 2.3.5, GCC 9.4.0] on linux
Operating System: Ubuntu 18.04

**Comment by kmod** [comment]
Thanks for submitting all of these issues! Sadly though we've stopped working on this project and aren't able to support it with bugfixes.

For this particular issue I tried running your code and I got the expected output (ie not what you got). I'm not able to help figure out where this difference comes from, but if you're interested in still running Pyston you could potentially try a newer operating system or one of our different packages from the same release or potentially building from source yourself. Sorry I can't be of more help!

I've disabled issue creation and I'll try to make it more clear what state the project is in.

**Comment by zzl261004** [comment]
Will users not be allowed to create issue in the future?

**Comment by zzl261004** [comment]
> 感谢您提交所有这些问题！遗憾的是，我们已经停止了这个项目，无法通过错误修复来支持它。
> 
> 对于这个特定的问题，我尝试运行您的代码，并获得了预期的输出（即不是您得到的结果）。我无法帮助找出哪里的差异，但如果您有兴趣可以继续运行 Pyston，您尝试更新或使用相同版本的不同的，或者自己从源代码构建。很遗憾我无法提供更多帮助！
> 
> 我已经取消了问题创建，请尝试更清楚地说明项目的状态。

Will users not be allowed to create issue in the future?

**Comment by kmod** [comment]
I left issues open but set it to give a warning when you do -- completely turning off issues felt overkill, especially since it would hide and disable all existing issues. I just wouldn't want anyone to invest time in writing issues since we're not going to respond to them.
