### ISSUE TITLE
Use pyston along side or instead of pyston3

### ISSUE THREAD

**Issue by AverageComet250** [pyston/pyston_v2#32]
The current command to execute pyston is currently `pyston3`. 

I understand that this is done to mirror python itself, but creating a second symlink named `pyston` or replacing the `pyston3` symlink may be a better option, as there is no version of pyston that is using that symlink, unlike the `python` symlink which is used by py 2.

**Comment by kmod** [comment]
I don't have a strong opinion on this, and my default would be to not provide it because it's easier to add it later than to remove it. Anyone else have an opinion?

**Comment by kmod** [comment]
Oh I was confused, are you talking about when you run `make`? It looks like our distribution package installs the `pyston` symlink

**Comment by AverageComet250** [comment]
To run pyston toy use the `pyston3` command. Can we have a symlink named just `pyston` alongside or instead of the `pyston3` symlink.

**Comment by kmod** [comment]
I believe what you are asking for already exists. If it doesn't for you, could you provide some more detail about how you installed pyston?

**Comment by AverageComet250** [comment]
I'm running pyston2.2 on Ubuntu wsl2 and I installed from the `deb` file.

At the minute, I have `pip-pyston3` aliased to `pip` and `pyston3` aliased to `pyston`, but I'd like it if the second alias was a symlink, and there was a better command for the package manager, like ppm (pyston package manager), which is exactly the same as pip but with a different command

**Comment by kmod** [comment]
Hmm I'm not sure what to say, it works for me:

```
$ wget https://github.com/pyston/pyston/releases/download/pyston_2.2/pyston_2.2_20.04.deb
$ sudo apt install ./pyston_2.2_20.04.deb
$ pyston
Python 3.8.8 (heads/rel2.2:6287d61613, Apr 29 2021, 15:46:12)
[Pyston 2.2.0, GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Could you try uninstalling pyston and reinstalling by these steps and let me know if it works for you?

**Comment by AverageComet250** [comment]
Maybe it didn't install properly since I downloaded the file and installed it from my windows downloads folder

**Comment by undingen** [comment]
Closing this issue because it seems it's working now. If you are still having problems please open it again.
