### ISSUE TITLE
Performance improvement confirmed in web frameworks.

### ISSUE THREAD

**Issue by GoodManWEN** [pyston/pyston_v2#33]
Hi,
Great news pysthon2.2 is released, thanks for the work of you guys. This issue is not intended for enhancement or bug fix request,  this is feedback from a past issue [#1442](https://github.com/pyston/pyston_v1/issues/1442#issuecomment-769391284) (_Originally posted by @GoodManWEN in https://github.com/pyston/pyston_v1/issues/1442#issuecomment-769391284_). In which I found that running the uvloop embedded web framework on pyston slows down instead of making it faster.

After the 2.2 release I re-tested it using the code mentioned in previous issue, here's the new result:
pysthon2.2 with native event loop
```
root@vm:~$ wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.31ms    1.62ms  20.74ms   75.80%
    Req/Sec     6.16k     2.36k   13.40k    70.40%
  613411 requests in 20.01s, 98.86MB read
Requests/sec:  30656.66
Transfer/sec:      4.94MB
```
pyston2.2 with uvloop
```
root@vm:~$ wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.48ms    1.23ms  30.65ms   74.79%
    Req/Sec     8.25k     1.61k   12.96k    67.80%
  820583 requests in 20.02s, 132.25MB read
Requests/sec:  40982.18
Transfer/sec:      6.61MB
```
Which shows a 41% improvement from cpython with in event loop, 40% faster than pyston2.1, and 14% faster than cpython3.8 with uvloop.

Thanks again!

**Comment by undingen** [comment]
Thanks for trying it out with pyston2.2 :smile:. 
I'm glad to hear that the performance improved noticeable.
