### ISSUE TITLE
I have tried to do your steps they don't work 

### ISSUE THREAD

**Issue by grizzlysmit** [pyston/pyston_v2#34]
I get 
```
23:41:16 θ60° grizzlysmit@pern:~/Projects/python3/pyston $ git submodule update --init pyston/llvm pyston/bolt/bolt pyston/bolt/llvm pyston/LuaJIT pyston/macrobenchmarks
fatal: not a git repository (or any of the parent directories): .git
```
I guess I need to clone the pyston git hub  first but I cannot get the link what gives

I was following https://github.com/pyston/pyston#readme

**Comment by undingen** [comment]
I think you downloaded the source code as archive and that's why it can't initialize the submodules.
To fix this you can either `git clone` our repo or try instead this source archive https://github.com/pyston/pyston/releases/download/pyston_2.2/pyston_2.2_src.tar.gz which should contain all required submodules.

**Comment by grizzlysmit** [comment]
I am complaining that I cannot find the link to  git clone with, as  for that release you point me to I have tried that too and it doesn't work either: first it died on a load of dependency errors when I added valgrid and a few others in the hope of fixing this I got a similar error about something not being not a git repository etc 
I have since run make clean and make all, but my real problem maybe that I am running Ubuntu 21.04 Desktop and I had to substitute python3.9-dev  etc as python3.8-dev dopes not exist in the Ubuntu repository for 21.04 anymore, I may have to try this on a `VM` with an earlier version on it, but one of my main points still holds I cannot find the github button to, There you go make all finished

```
Successfully installed pip-20.2.3 setuptools-49.2.1
make[1]: Leaving directory '/home/grizzlysmit/Projects/python3/pyston/pyston/pyston/build/cpython_opt_build'
mkdir -p pyston/build/bolt
cd pyston/build/bolt; cmake -G Ninja ../../bolt/llvm -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
CMake Deprecation Warning at CMakeLists.txt:14 (cmake_policy):
  The OLD behavior for policy CMP0051 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings enabled.
-- OCaml bindings disabled, need ctypes >=0.4.
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- Targeting X86
-- Targeting llvm-bolt X86
fatal: not a git repository: /home/grizzlysmit/Projects/python3/pyston/pyston/pyston/bolt/llvm/../../../.git/modules/pyston/bolt/llvm
CMake Error at CMakeLists.txt:908 (add_subdirectory):
  add_subdirectory given source "test" which is not an existing directory.


-- Configuring incomplete, errors occurred!
See also "/home/grizzlysmit/Projects/python3/pyston/pyston/pyston/build/bolt/CMakeFiles/CMakeOutput.log".
See also "/home/grizzlysmit/Projects/python3/pyston/pyston/pyston/build/bolt/CMakeFiles/CMakeError.log".
make: *** [Makefile:66: pyston/build/bolt/build.ninja] Error 1
```

**Comment by grizzlysmit** [comment]
what distro/version do you recomend for testing this on

**Comment by undingen** [comment]
I'm currently trying to compile it on 21.04 and will report back with instructions.

If you just want to run pyston and compiling your own is not a requirement you can use the portable package `pyston_2.2_portable.tar.gz` which should run on 21.04.

If you want to compile it yourself: I'm developing on 20.04.

**Comment by undingen** [comment]
I could build it on 21.04 using the following instructions: 
```
sudo apt-get install build-essential git libjpeg-dev
sudo apt-get install ninja-build cmake clang libssl-dev libsqlite3-dev luajit python3 zlib1g-dev virtualenv libjemalloc-dev
git clone https://github.com/pyston/pyston.git
cd pyston
git submodule update --init pyston/llvm pyston/bolt/bolt pyston/bolt/llvm pyston/LuaJIT pyston/macrobenchmarks
make -j
```
You can find pyston afterwards inside: `pyston/build/cpython_opt_install/`

**Comment by grizzlysmit** [comment]
OK I've found something the reason I could not find the code button has something to do with my github login I  went to the site (this site) from the `VM` of 20.04 that I made and I could see it and I got the https link for it (I would normally get the ssh link) but apparently that is only avail if you have an account and a ssh key registered I guess any way I've cloned it now

**Comment by grizzlysmit** [comment]
OK your instructions worked once I was able to clone the repo but how can I install it all on my box 
hmm it's mostly not conflicting except for `pyston/build/cpython_opt_install/usr/bin/pip3` & `/usr/bin/pip3` maybe I could rename `pyston/build/cpython_opt_install/usr/bin/pip3` to `pyston/build/cpython_opt_install/usr/bin/pip3-pyston then I should be safe to install globally 

Umm should this thread be preserved as there is much useful info in here

**Comment by kmod** [comment]
Ah looks like there are some lingering issues with the source distribution, I'll fix them shortly

**Comment by kmod** [comment]
Ok I've reuploaded the source release and it should fix the problem you ran into. I'm testing it again to make sure there aren't other issues.

**Comment by grizzlysmit** [comment]
thank you very much you've been a great help

**Comment by undingen** [comment]
I'm closing this issue the source release should be fixed now.
