### ISSUE TITLE
can't install uwsgi

### ISSUE THREAD

**Issue by wynnw** [pyston/pyston_v2#35]
Repro steps using the pyston_2.2_portable.tar.gz release:
`$ pyston2.2/pyston3.8 -m venv uwsgi-test
$ uwsgi-test/bin/pip install -U pip
$ uwsgi-test/bin/pip install uwsgi
`

This will fail with:
` gcc: error: /home/wynnw/uwsgi-test/lib/python3.8/config-3.8/libpython3.8.a: No such file or directory`

You're probably aware of this due to the decision not to provide a .a lib (I don't see one in your release tar.gz) or maybe there's something else that breaks a package's python lib detection?

Anyways, great work. I've seen excellent speedups for our flake8/pylint runs which are a huge pain point for us. But, I can't install our standard requirements.txt dependencies completely currently due to several issues like this.

**Comment by undingen** [comment]
Thanks for the report. 
At the moment we don't support embedding pyston that's why we don't provide a `.a`/`.so` but we
are currently working on adding support for it (we have `uwsgi` in mind).

**Comment by undingen** [comment]
We added embedding support in [v2.3](https://github.com/pyston/pyston/releases/tag/v2.3) and explicitly test with uwsgi so this should be fixed supported now. 
Unfortunately it currently only works with the debian packages (the portable release contains the library but uwsgi can't find it)
