### ISSUE TITLE
Some packages don't build/install properly

### ISSUE THREAD

**Issue by dmrlawson** [pyston/pyston_v2#42]
Hi,

So far I've seen really good results from Pyston and it's been very easy to test different projects on it so thank you.

I've found that some packages are not compiling properly or they're not installing properly, I'm not sure which. The examples I've seen tend to use cffi or cython so I'm not sure if it's because Pyston re-compiles them rather than using wheels (and is thus exposing packages that aren't defined properly) or if it's conflicting somehow with the pip cache and other cpython 3.8 installations.

 Here's an example I can reproduce with gevent:

```
david@davitude:~$ pyenv install pyston-2.2

WARNING: Pyston only runs on x86_64 platforms, and only has been tested on Ubuntu
so, your mileage may vary with other Linux distributions.

Downloading pyston_2.2.tar.gz...
-> https://github.com/pyston/pyston/releases/download/pyston_2.2/pyston_2.2_portable.tar.gz
Installing pyston_2.2...
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Installed pyston_2.2 to /home/david/.pyenv/versions/pyston-2.2

david@davitude:~$ ~/.pyenv/versions/pyston-2.2/bin/python -m pip install gevent
Collecting gevent
  Downloading gevent-21.1.2.tar.gz (5.9 MB)
     |████████████████████████████████| 5.9 MB 4.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting zope.event
  Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: setuptools in ./.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages (from gevent) (49.2.1)
Collecting greenlet<2.0,>=0.4.17; platform_python_implementation == "CPython"
  Using cached greenlet-1.1.0.tar.gz (85 kB)
Collecting zope.interface
  Downloading zope.interface-5.4.0.tar.gz (249 kB)
     |████████████████████████████████| 249 kB 7.0 MB/s 
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for zope.interface, since package 'wheel' is not installed.
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) ... done
  Created wheel for gevent: filename=gevent-21.1.2-pyston38-pyston_22_x86_64_linux_gnu-linux_x86_64.whl size=6481324 sha256=e7ab7cf83e881dd82825e817b7e44318d0c87268721749c96961a075b9c4e74e
  Stored in directory: /home/david/.cache/pip/wheels/95/40/df/1b390c39ed0c1cf1b0f27da783eb74498db6e4b1d04abd86c6
Successfully built gevent
Installing collected packages: zope.event, greenlet, zope.interface, gevent
    Running setup.py install for greenlet ... done
    Running setup.py install for zope.interface ... done
Successfully installed gevent-21.1.2 greenlet-1.1.0 zope.event-4.5.0 zope.interface-5.4.0
WARNING: You are using pip version 20.2.3; however, version 21.1.2 is available.
You should consider upgrading via the '/home/david/.pyenv/versions/pyston-2.2/bin/python -m pip install --upgrade pip' command.
david@davitude:~$ ~/.pyenv/versions/pyston-2.2/bin/python -c "from gevent.monkey import is_object_patched"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/__init__.py", line 85, in <module>
    from gevent._config import config
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/_config.py", line 699, in <module>
    Loop().get()
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/_config.py", line 219, in _import_one_of
    return self._import_one(item)
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/home/david/.pyenv/versions/pyston-2.2/lib/pyston3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/libev/corecext.pyx", line 979, in init gevent.libev.corecext
SystemError: Bad call flags for CyFunction
```

In some circumstances which I haven't narrowed down yet it does work so I don't think it's an API issue but perhaps something to do with pip? With the cffi package I was trying it appears to work if I install cffi first, which is different in behaviour to cpython 3.8.

**Comment by undingen** [comment]
Thanks for reporting the bug!
I'm currently investigating what caused it and how to fix it.

Copying in the investigation from discord:

It seems to be caused by a memory corruption/out of bounds write:
It looks like cython in temporarily setting `Py_TPFLAGS_HEAPTYPE` inside `__Pyx_PyType_Ready` on the passed `PyTypeObject`:
![image](https://user-images.githubusercontent.com/7397630/119847653-72699680-bf0b-11eb-9e71-b28bdf980b1a.png)
https://github.com/cython/cython/blob/6889482cebefe93d5599b56f3a0389224e92bff5/Cython/Utility/ExtensionTypes.c#L118

Because `Py_TPFLAGS_HEAPTYPE` is set we cast the type to the larger `PyHeapTypeObject` type and clear some fields. But this fields are actually out of bounds because cython never passed us a `PyHeapTypeObject` (we got a smaller `PyTypeObject`)
![image](https://user-images.githubusercontent.com/7397630/119847717-83b2a300-bf0b-11eb-899e-ed421f541f8e.png)

https://github.com/pyston/pyston/blob/832ec0d76facb2e1e958324c7c1ce2c3879283ca/Objects/typeobject.c#L281

To me this looks like a bug inside cython but I have to investigate further. Not sure why we did not run into this issue earlier but maybe it was just luck.

**Comment by undingen** [comment]
Cython 3.0.0a8 got released which contains the fix for pyston :fireworks: .
Installing gevent should now work again (tested with latest gevent 21.1.2 which previously failed).

Hope this resolves the issue for you.

**Comment by dmrlawson** [comment]
Thank you! It seems to work again.

For anyone else: I had to delete my `~/.cache/pip` directory before it would install properly (presumably after the failed builds)

**Comment by aisk** [comment]
@dmrlawson You can use the ` --no-cache-dir` flag in pip to avoid using cache.
