### ISSUE TITLE
QUESTION: Packaging and running

### ISSUE THREAD

**Issue by ghost** [pyston/pyston_v2#58]
I'm interested in running a high-performance script using a concurrent architecture, but I'd like to know if It is better to create a bundle of my script along with its dependencies when packaging before running the script using Pyston, or is it possible to install the dependencies with a tool like pip or Pyston is able to load those dependencies from the site-packages folder.

This is the list of dependencies I'm using in my script:
- [asyncio = "==3.4.3"](https://pypi.org/project/asyncio/)
- [python-binance = "==1.0.12"](https://pypi.org/project/python-binance/)
- [PyYAML = "==5.4.1"](https://pypi.org/project/PyYAML/)

Running on Python version: 3.8.5

Thanks for advance,

Amazing project you're working on.

**Comment by undingen** [comment]
You should be able to use pip like usual (either via `pyston-pip` or `pyston -mpip`). You can then install via requirements file etc.
Directly reusing a site-packages directory from cpython will not work because we are not ABI compatible so you will have to install inside pyston,

E.g.
```bash
$ docker run -it --rm ubuntu:20.04
root@04e92dfd5f0f:/# apt-get update
root@04e92dfd5f0f:/# apt-get install build-essential wget
root@04e92dfd5f0f:/# wget https://github.com/pyston/pyston/releases/download/pyston_2.2/pyston_2.2_20.04.deb
root@04e92dfd5f0f:/# apt install ./pyston_2.2_20.04.deb
root@04e92dfd5f0f:/# pyston -mpip install asyncio==3.4.3 python-binance==1.0.12 PyYAML==5.4.1
```

Hope I understood your question correctly.

**Comment by ghost** [comment]
Exactly what I was looking for!! 

Thank you very much
