### ISSUE TITLE
 Running numpy.test() cause "Fatal Python error: Segmentation fault"

### ISSUE THREAD

**Issue by Schleehauf** [pyston/pyston_v2#62]
Running numpy tests, causes a segmentation fault.

Steps to reproduce:
1. create a venv
2. pip install numpy pytest hypothesis
          
          Respective package versions are:
          ~/pyston38$ pip freeze
          asv==0.4.2
          attrs==21.2.0
          hypothesis==6.14.1
          iniconfig==1.1.1
          numpy==1.21.0
          packaging==21.0
          pluggy==0.13.1
          py==1.10.0
          pyparsing==2.4.7
          pytest==6.2.4
          six==1.16.0
          sortedcontainers==2.4.0
          toml==0.10.2

**3. Start interpreter and run tests:**

Python 3.8.8 (heads/rel2.2:6287d61613, Apr 29 2021, 15:46:12)
[Pyston 2.2.0, GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.test()
NumPy version 1.21.0
NumPy relaxed strides checking option: True
NumPy CPU features:  SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C? FMA3? AVX2? AVX512F? AVX512CD? AVX512_KNL? AVX512_KNM? AVX512_SKX? AVX512_CLX? AVX512_CNL? AVX512_ICL?
........................................................................ [  0%]
..............................................................x......... [  0%]
........................................................................ [  1%]
........................................................x............... [  1%]
........................................................................ [  2%]
........................................................................ [  2%]
........................................................................ [  3%]
...............................ssssssss................................. [  3%]
........................................................................ [  4%]
..............s......................................................... [  4%]
............................................x..........x..x..........x.. [  5%]
........................................................................ [  5%]
..................s..................................................... [  6%]
......ssssssss.......................................................... [  6%]
....................................ssss................................ [  6%]
...Fatal Python error: Segmentation fault

Current thread 0x00007fd74ebb1280 (most recent call first):
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/numpy/core/tests/test_dtype.py", line 812 in test_list_recursion
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/python.py", line 1641 in runtest
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/main.py", line 323 in _main
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/wohnzimmer/pyston38/lib/pyston3.8/site-packages/numpy/_pytesttester.py", line 197 in __call__
  File "<stdin>", line 1 in <module>

**Expected output (from  running cpython):**

Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.test()
NumPy version 1.21.0
NumPy relaxed strides checking option: True
NumPy CPU features:  SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C? FMA3? AVX2? AVX512F? AVX512CD? AVX512_KNL? AVX512_KNM? AVX512_SKX? AVX512_CLX? AVX512_CNL? AVX512_ICL?
........................................................................ [  0%]
...........s....s.ss.................................................... [  1%]
ss.....s............................x................................... [  1%]
.................................s...................................... [  2%]
............................ss.........................................s [  2%]
sssssss................................................................. [  3%]
......................................................s................. [  3%]
........................................................................ [  4%]
............x..........x..x..........x.................................. [  4%]
..........................................................s............. [  5%]
..............................................ssssssss.................. [  5%]
........................................................................ [  6%]
....sssssssss........................................................... [  6%]
........................................................................ [  7%]
................................................s....................... [  7%]
........................................................................ [  8%]
........................................................................ [  8%]
........................................................................ [  9%]
................ssssssssss.............................................. [  9%]
........................................................................ [ 10%]
.............................xx......................................... [ 10%]
........................................................................ [ 11%]
................s....................................................... [ 11%]
................................................................s.s.s.s. [ 12%]
s.s.....s.s.....s.s.s.s.......s.s.s.s................................... [ 12%]
........................................................................ [ 13%]
........................................................................ [ 13%]
........................................................................ [ 14%]
........................................................................ [ 14%]
........................................................................ [ 15%]
........................................................................ [ 15%]
........................................................................ [ 16%]
........................................................................ [ 16%]
........................................................................ [ 17%]
........................................................................ [ 17%]
........................................................................ [ 18%]
........................................................................ [ 18%]
........................................................................ [ 19%]
........................................................................ [ 19%]
........................................................................ [ 20%]
........................................................................ [ 20%]
.........................................................x...x.......... [ 21%]
........................................................................ [ 21%]
........................................................................ [ 22%]
............................xx.......................................... [ 22%]
........................................................................ [ 23%]
........................................................................ [ 23%]
........................................................................ [ 24%]
........................................................................ [ 24%]
.......sss.............................................................. [ 25%]
........................................................................ [ 25%]
........................................................................ [ 26%]
........................................................................ [ 26%]
........................................................................ [ 27%]
........................................................................ [ 27%]
........................................................................ [ 28%]
........................................................................ [ 28%]
........................................................................ [ 29%]
........................................................................ [ 29%]
...............................s........................................ [ 30%]
.....................................................................s.. [ 30%]
........................................................................ [ 31%]
........................................................................ [ 31%]
...................................sssssssssssssssssssssssssssssssssssss [ 32%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 32%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 33%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 33%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 34%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 34%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 35%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 35%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 36%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 36%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 37%]
sssssssssssssssssssssssssssssssssssssssssssssssssssss................... [ 37%]
........................................................................ [ 38%]
........................................................................ [ 38%]
........................................................................ [ 39%]
........................................................................ [ 39%]
........................................................................ [ 40%]
........................................................................ [ 40%]
........................................................................ [ 41%]
........................................................................ [ 41%]
........................................................................ [ 42%]
........................................................................ [ 42%]
........................................................................ [ 43%]
........................................................................ [ 43%]
........................................................................ [ 44%]
......................ss................................................ [ 44%]
........................................................................ [ 45%]
........................................................................ [ 45%]
..................................................................s..s.. [ 46%]
..........s............................................................. [ 46%]
........................................................................ [ 47%]
........................................................................ [ 47%]
........................................................................ [ 48%]
........................................................................ [ 48%]
........................................................................ [ 49%]
........................................................................ [ 49%]
........................................................................ [ 50%]
........................................................................ [ 50%]
................s...........sssssssssssssss...............ssssssssssssss [ 51%]
s....................................................................... [ 51%]
........................................................................ [ 52%]
........................................................................ [ 52%]
........................................................................ [ 53%]
........................................................................ [ 53%]
........................................................................ [ 54%]
........................................................................ [ 54%]
........................................................................ [ 55%]
........................................................................ [ 55%]
........................................................................ [ 56%]
........................................................................ [ 56%]
.............................................................x.......... [ 57%]
........................................................................ [ 57%]
........................................................................ [ 58%]
........................................................................ [ 58%]
........................................................................ [ 59%]
........................................................................ [ 59%]
........................................................................ [ 60%]
........................................................................ [ 60%]
........................................................................ [ 61%]
........................................................................ [ 61%]
......................................................................x. [ 62%]
........................................................................ [ 62%]
........................................................................ [ 63%]
........................................................................ [ 63%]
........................................................................ [ 64%]
........................................................................ [ 64%]
........................................................................ [ 65%]
........................................................................ [ 65%]
........................................................................ [ 66%]
.............................................................ss..ss..... [ 66%]
.............................................................x.......... [ 67%]
........................................................................ [ 67%]
........................................................................ [ 68%]
........................................................................ [ 68%]
.........................................................x.............. [ 69%]
........................................................................ [ 69%]
........................................................................ [ 70%]
........................................................................ [ 70%]
.................x...................................................... [ 71%]
........................................................................ [ 71%]
........................................................................ [ 72%]
........................................................................ [ 72%]
........................................................................ [ 73%]
........................................................................ [ 73%]
........................................................................ [ 74%]
........................................................................ [ 74%]
........................................................................ [ 75%]
........................................................................ [ 75%]
........................................................................ [ 76%]
........................................................................ [ 76%]
........................................................................ [ 77%]
........................................................................ [ 77%]
........................................................................ [ 78%]
........................................................................ [ 78%]
........................................................................ [ 79%]
........................................................................ [ 79%]
........................................................................ [ 80%]
........................................................................ [ 80%]
....................xx.................................................. [ 81%]
........................................................................ [ 81%]
........................................................................ [ 82%]
........................................................................ [ 82%]
........................................................................ [ 83%]
........................................................................ [ 83%]
........................................................................ [ 84%]
........................................................................ [ 84%]
........................................................................ [ 85%]
........................................................................ [ 85%]
........................................................................ [ 86%]
........................................................................ [ 86%]
........................................................................ [ 87%]
........................................................................ [ 87%]
........................................................................ [ 88%]
........................................................................ [ 88%]
.....................s................s................s................ [ 89%]
s.................s....ss............................................... [ 89%]
........................................................................ [ 90%]
........................................................................ [ 90%]
........................................................................ [ 91%]
........................................................................ [ 91%]
........................................................................ [ 92%]
........................................................................ [ 92%]
........................................................................ [ 93%]
........................................................................ [ 93%]
...............s........................................................ [ 94%]
........................................................................ [ 94%]
........................................................................ [ 95%]
........................................................................ [ 95%]
..................ss.................................................... [ 96%]
........................................................................ [ 96%]
........................................................................ [ 97%]
........................................................................ [ 97%]
....................................................................sss. [ 98%]
........................................................................ [ 98%]
................XXX..................................................... [ 99%]
........................................................................ [ 99%]
..................................................................       [100%]
13440 passed, 933 skipped, 115 deselected, 18 xfailed, 3 xpassed in 135.20s (0:02:15)
True
>>>

**Comment by kmod** [comment]
This is because the numpy testsuite has infinite-recursion tests, and we disabled recursion-limit checking in Pyston so the errors they expect are now segfaults. We've been meaning to address this particular case by submitting a patch to numpy to disable the recursion tests when run on Pyston.

**Comment by Schleehauf** [comment]
I started to write a patch for numpy, appart from the recursion there are 2 more failing tests for which I would like to double check with you that they should be skipped.

1. Tests failing due to recusion are fixed (skipped) in https://github.com/Schleehauf/numpy/commit/f5fcd004956c7c6a7699d73a9fd687f145f7cc29

2. There is one test failure concerning refcounting, I am not sure if this should just be skipped aswell

  self = <numpy.core.tests.test_numeric.TestCreationFuncs object at 0x7f01dcdc3d90>

    @pytest.mark.skipif(not HAS_REFCOUNT, reason="Python lacks refcounts")
    def test_for_reference_leak(self):
        # Make sure we have an object for reference
        dim = 1
        beg = sys.getrefcount(dim)
        np.zeros([dim]*10)
        print(f'REFCOUNT CHECK zeros {sys.getrefcount(dim) ==beg} {sys.getrefcount(dim)} != {beg}\n')
        #assert_(sys.getrefcount(dim) == beg)
        np.ones([dim]*10)
        print(f'REFCOUNT CHECK ones2 {sys.getrefcount(dim) == beg} {sys.getrefcount(dim)} != {beg}\n')
        #assert_(sys.getrefcount(dim) == beg)
        np.empty([dim]*10)
        print(f'REFCOUNT CHECK empty {sys.getrefcount(dim) == beg} {sys.getrefcount(dim)} != {beg}\n')
        #assert_(sys.getrefcount(dim) == beg)
        np.full([dim]*10, 0)
        print(f'REFCOUNT CHECK full {sys.getrefcount(dim) == beg} {sys.getrefcount(dim)} != {beg}\n')
        #assert_(sys.getrefcount(dim) == beg)

  REFCOUNT CHECK zeros True 1152921504606921166 != 1152921504606921166
  REFCOUNT CHECK ones2 False 1152921504606921165 != 1152921504606921166
  REFCOUNT CHECK empty False 1152921504606921165 != 1152921504606921166
  REFCOUNT CHECK full False 1152921504606921165 != 1152921504606921166

3. The last one is about importing distutils, in warn_distutils_present():  

____________________________________________________________________________________ test_api_importable _____________________________________________________________________________________

    def test_api_importable():
        """
        Check that all submodules listed higher up in this file can be imported
    
        Note that if a PRIVATE_BUT_PRESENT_MODULES entry goes missing, it may
        simply need to be removed from the list (deprecation may or may not be
        needed - apply common sense).
        """
        def check_importable(module_name):
            try:
                importlib.import_module(module_name)
            except (ImportError, AttributeError):
                return False
    
            return True
    
        module_names = []
        for module_name in PUBLIC_MODULES:
            if not check_importable(module_name):
                module_names.append(module_name)
    
        if module_names:
            raise AssertionError("Modules in the public API that cannot be "
                                 "imported: {}".format(module_names))
    
        for module_name in PUBLIC_ALIASED_MODULES:
            try:
                eval(module_name)
            except AttributeError:
                module_names.append(module_name)
    
        if module_names:
            raise AssertionError("Modules in the public API that were not "
                                 "found: {}".format(module_names))
    
        with warnings.catch_warnings(record=True) as w:
            warnings.filterwarnings('always', category=DeprecationWarning)
            warnings.filterwarnings('always', category=ImportWarning)
            for module_name in PRIVATE_BUT_PRESENT_MODULES:
>               if not check_importable(module_name):

check_importable = <function test_api_importable.<locals>.check_importable at 0x7f01df438f70>
module_name = 'numpy.distutils.command.develop'
module_names = []
w          = [<warnings.WarningMessage object at 0x7f01c597c280>]

numpy/tests/test_public_api.py:469: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
numpy/tests/test_public_api.py:440: in check_importable
    importlib.import_module(module_name)
        module_name = 'numpy.distutils.command.develop'
/usr/lib/pyston3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
        level      = 0
        name       = 'numpy.distutils.command.develop'
        package    = None
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
        level      = 0
        name       = 'numpy.distutils.command.develop'
        package    = None
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
        import_    = <function _gcd_import at 0x7f01ea2aa4c0>
        module     = <object object at 0x7f01ea281060>
        name       = 'numpy.distutils.command.develop'
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
        import_    = <function _gcd_import at 0x7f01ea2aa4c0>
        name       = 'numpy.distutils.command.develop'
        parent     = 'numpy.distutils.command'
        parent_module = <module 'numpy.distutils.command' from '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/__init__.py'>
        path       = ['/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command']
        spec       = ModuleSpec(name='numpy.distutils.command.develop', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f0...580>, origin='/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py')
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
        module     = <module 'numpy.distutils.command.develop' from '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py'>
        spec       = ModuleSpec(name='numpy.distutils.command.develop', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f0...580>, origin='/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py')
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
        code       = <code object <module> at 0x7f01c58d0780, file "/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py", line 1>
        module     = <module 'numpy.distutils.command.develop' from '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py'>
        self       = <_frozen_importlib_external.SourceFileLoader object at 0x7f01c597c580>
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
        args       = (<code object <module> at 0x7f01c58d0780, file "/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/n...le__': '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py', ...})
        f          = <built-in function exec>
        kwds       = {}
numpy/distutils/command/develop.py:6: in <module>
    from setuptools.command.develop import develop as old_develop
        __builtins__ = <builtins>
        __cached__ = '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/__pycache__/develop.pyston-22.pyc'
        __doc__    = ' Override the develop command from setuptools so we can ensure that our\ngenerated files (from build_src or build_scripts) are properly converted to real\nfiles with filenames.\n\n'
        __file__   = '/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f01c597c580>
        __name__   = 'numpy.distutils.command.develop'
        __package__ = 'numpy.distutils.command'
        __spec__   = ModuleSpec(name='numpy.distutils.command.develop', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f0...580>, origin='/home/wohnzimmer/src/numpy/build/testenv/lib/pyston3.8/site-packages/numpy/distutils/command/develop.py')
/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/__init__.py:7: in <module>
    import setuptools.distutils_patch  # noqa: F401
        __builtins__ = <builtins>
        __cached__ = '/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/__pycache__/__init__.pyston-22.pyc'
        __doc__    = "Extensions to the 'distutils' for large or complex distributions"
        __file__   = '/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f01c5932280>
        __name__   = 'setuptools'
        __package__ = 'setuptools'
        __path__   = ['/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools']
        __spec__   = ModuleSpec(name='setuptools', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f01c5932280>, origin='/...ols/__init__.py', submodule_search_locations=['/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools'])
        functools  = <module 'functools' from '/usr/lib/pyston3.8/functools.py'>
        os         = <module 'os' from '/usr/lib/pyston3.8/os.py'>
/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/distutils_patch.py:59: in <module>
    warn_distutils_present()
        __builtins__ = <builtins>
        __cached__ = '/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/__pycache__/distutils_patch.pyston-22.pyc'
        __doc__    = '\nEnsure that the local copy of distutils is preferred over stdlib.\n\nSee https://github.com/pypa/setuptools/issues/417#issuecomment-392298401\nfor more motivation.\n'
        __file__   = '/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/distutils_patch.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f01c5932f40>
        __name__   = 'setuptools.distutils_patch'
        __package__ = 'setuptools'
        __spec__   = ModuleSpec(name='setuptools.distutils_patch', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f01c5932f40>, origin='/home/wohnzimmer/pyston_np_env/lib/pyston3.8/site-packages/setuptools/distutils_patch.py')
        __warningregistry__ = {'version': 385534}
        clear_distutils = <function clear_distutils at 0x7f01df438940>
        enabled    = <function enabled at 0x7f01df438310>
        ensure_local_distutils = <function ensure_local_distutils at 0x7f01df438a60>
        importlib  = <module 'importlib' from '/usr/lib/pyston3.8/importlib/__init__.py'>
        is_pypy    = False
        os         = <module 'os' from '/usr/lib/pyston3.8/os.py'>
        re         = <module 're' from '/usr/lib/pyston3.8/re.py'>
        sys        = <module 'sys' (built-in)>
        warn_distutils_present = <function warn_distutils_present at 0x7f01df438dc0>
        warnings   = <module 'warnings' from '/usr/lib/pyston3.8/warnings.py'>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def warn_distutils_present():
        if 'distutils' not in sys.modules:
            return
        if is_pypy and sys.version_info < (3, 7):
            # PyPy for 3.6 unconditionally imports distutils, so bypass the warning
            # https://foss.heptapod.net/pypy/pypy/-/blob/be829135bc0d758997b3566062999ee8b23872b4/lib-python/3/site.py#L250
            return
>       warnings.warn(
            "Distutils was imported before Setuptools. This usage is discouraged "
            "and may exhibit undesirable behaviors or errors. Please use "
            "Setuptools' objects directly or at least import Setuptools first.")
E       UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.

**Comment by kmod** [comment]
Yes the second one should be skipped as well -- we set the refcount of "immortal" objects to ~infinity and then skip refcounting operations on them as much as possible, which means that their refcounts behave erratically and tests like this won't pass.

I'm not sure about the third one, though one thing we've found in general is that many test suites don't pass by default, so our integration test runner only checks that we pass as many tests as the system python does. If this is passing in your system python then I can take a look at it shortly.

thanks for looking into this!

**Comment by kmod** [comment]
I was unable to reproduce your third issue and I suspect an environment difference, could you let me know how you installed pyston? And if you do have a chance it'd be interesting to know if that test is passing on CPython.

**Comment by Schleehauf** [comment]
I installed the package via dpkg. After  upgrading pip and setuptools from 

      pip        20.2.3
      setuptools 49.2.1 

to 

      pip        21.1.3
      setuptools 57.1.0

the test passes without any failure, thus I didn't try to reproduce on cpython. For the other two I created a pull request https://github.com/numpy/numpy/pull/19423

**Comment by kmod** [comment]
Thanks for taking care of this for us!
