### ISSUE TITLE
How to get LLVM IR from Pyston_v2.2

### ISSUE THREAD

**Issue by persuingL** [pyston/pyston_v2#63]
I want to get LLVM IR generated by pyston.

**Comment by kmod** [comment]
We no longer use LLVM as our jit, so we don't generate LLVM IR at runtime.

If you'd like to see the x86 assembly we generate you can do something like
```
make pyston/macrobenchmarks/benchmarks/perf_djangocms_unopt
```
which will show you perf stats, and you can press "a" to see a source disassembly.

If you'd like to see the LLVM IR we generate for our quickening traces, first do `make` and then you can inspect the files in `pyston/build/aot/`

Let me know if that answers your question!
