### ISSUE TITLE
.pyc files included in the v2.3 deb files have the wrong timestamp

### ISSUE THREAD

**Issue by gurnec** [pyston/pyston_v2#70]
In at least the `pyston_2.3_20.04.deb` file (I didn't check the others) from the recently released [v2.3](https://github.com/pyston/pyston/releases/tag/v2.3), the timestamps stored inside the `.pyc` files do not match the last-modified times of the corresponding `.py` files. As a result, either:

 * If running pyston as non-root, the `.pyc` files are not used and the `.py` files are recompiled each time.
 * If running as root, the `.pyc` files are replaced (after which they are used normally).

Perhaps something in the build process changed the timestamps of all of the `.py` files after they were compiled into `.pyc`s?

As an example, `secrets.py` has a last-modified time of 2021-07-08 15:46:12 UTC (0x60e71dc4 past the epoch), however `__pycache__/secrets.pyston-23.pyc` includes the timestamp 0x60f0ad96 (inside the file at offset 8 in little-endian format) which apparently was the last-modified time of `secret.py` when the `.pyc` file was compiled (2021-07-15 21:50:14 UTC).

**Comment by undingen** [comment]
Sorry for the late response, just came back from holiday.
Nice catch and thanks for the detailed description! :1st_place_medal: 
This is something we want fixed in the next release for sure.

**Comment by gurnec** [comment]
No worries. I hope you enjoyed your holiday!
