### ISSUE TITLE
Not a issue but

### ISSUE THREAD

**Issue by GoodManWEN** [pyston/pyston_v2#72]
Hey guys,

This is not a issue, just wanted to let you know that there are people who are following the growth of this project closely. I created a project to test the performance of pyston by automatically running the code of the debian's language performance test. I switched to version 2.3 right after it release, however in my tests v2.3 is not faster than 2.2 but actually got a 0.5% slower.

This is not some sort of suggestion, maybe this is meeting expectations, just wanted to let you know that. Anyway thanks for all your hard works.

**Comment by kmod** [comment]
Thanks for letting us know! We focused primarily on compatibility this release so we didn't expect much performance improvement, but that's surprising that you're seeing a regression. Is your performance test publicly available so we could check it out?

**Comment by GoodManWEN** [comment]
@kmod Glad to have your reply! I got a performance testing project for mainstream languages whose test items and code are derived from debian's [Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html), and I transformed it into a chart to quickly check out the magnitude of performance comparisons. You can check its details in this link [Programming-Language-Benchmarks-Visualization](https://github.com/GoodManWEN/Programming-Language-Benchmarks-Visualization).

To put it simply, it is automatically maintained by github actions. I checked the submission history, render in [767a978](https://github.com/GoodManWEN/Programming-Language-Benchmarks-Visualization/commit/767a978cf16675983b449e9b34a6877634cc18c7) got a result as follow:
![](https://raw.githubusercontent.com/GoodManWEN/Programming-Language-Benchmarks-Visualization/767a978cf16675983b449e9b34a6877634cc18c7/ranking.png)

And render in [8d554f5](https://github.com/GoodManWEN/Programming-Language-Benchmarks-Visualization/commit/8d554f5ce759de98a0b266f967477842534811d8) got:
![](https://raw.githubusercontent.com/GoodManWEN/Programming-Language-Benchmarks-Visualization/8d554f5ce759de98a0b266f967477842534811d8/ranking.png)

Which shows that Pyston2.3 elapses 34.42 times the time of C++, while Pyston2.2 elapses 34.32 times the time of C++, slowed down by about 0.5%  and takes up about 10% more memory on average. I manually checked that the new version is indeed based on the results of Python 2.3 and it uses also the same code.
