### ISSUE TITLE
Failed installation on Ubuntu WSL2

### ISSUE THREAD

**Issue by EmadMokhtar** [pyston/pyston_v2#74]
I'm running Ubuntu on WSL2. I tried to install both version 2.2 and 2.3. I installed them via the `.deb` package. When I run `pyston` or `pip-pyston` I got the following errors.

### pyston

``` bash
$ pyston
zsh: exec format error: pyston
$ sudo pyston
/usr/bin/pyston: 1: Syntax error: word unexpected (expecting ")")
```

### pip-pyston

``` bash
$ pip-pyston                                                           
zsh: exec format error: pip-pyston
$ sudo pip-pyston                                                     
/usr/bin/pip-pyston: 3: import: not found
/usr/bin/pip-pyston: 4: import: not found
from: can't read /var/mail/pip._internal.cli.main
/usr/bin/pip-pyston: 7: Syntax error: "(" unexpected (expecting "then")
```

## More information

I add these information, it may help.

``` bash
$ which pyston                                                          
/usr/bin/pyston
$ file /usr/bin/pyston                                                 
/usr/bin/pyston: symbolic link to pyston3.8  
$ uname -a                                                              
Linux MachineName 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
$ uname -r                                                              
4.4.0-19041-Microsoft
```

**Comment by EmadMokhtar** [comment]
I managed to install Pyston 2.2 via Pyenv in the same environment.

**Comment by kmod** [comment]
Very odd, I'm not quite sure what's going on here. It looks like your `/usr/bin/pyston` is coming from pyston2.2 (in 2.3 we have it point to a different file path), so it's probably worth uninstalling both and then reinstalling 2.3 again. Also are you sure this is WSL2? I get
```
$ uname -r
5.4.72-microsoft-standard-WSL2
```

**Comment by gurnec** [comment]
Assuming the `which` that @EmadMokhtar ran is correct, it is definitely WSL1, not WSL2. This is probably a WSL1 bug. If you [search for `exec format error` in the WSL issues repo](https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+%22exec+format+error%22), you'll see a few hits. It doesn't look like the exact cause has been found, and there may even be multiple bugs resulting in the same error message. You could try opening a new issue over there, however there's very little development work on WSL1 these days—I wouldn't expect a resolution.

I did find a workaround. I have no idea why it works, and as far as I can tell there's no reason it should work, but it does:

    sudo patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 /usr/bin/python3.8-pyston2.3

(You'll probably need to `sudo apt install patchelf` first.) This doesn't actually change the interpreter (it's the same before & after), but it causes the program header table to be rewritten, and for whatever reason WSL1 likes the new program header, but not the old one (at least that's what I'm guessing).

**Comment by undingen** [comment]
I'm closing this because it's a issue of WSL1 and WSL2 does not have the problem (for WSL1 following the instructions of @gurnec should fix it too (thanks again!)).
