### ISSUE TITLE
Remove the `-j` option in the README's instructions

### ISSUE THREAD

**Issue by esmaycat** [pyston/pyston_v2#78]
In the instructions for how to build pyston, the command `make -j` is listed as one of the steps to follow. I don't think that this should be included (or at least updated to have an argument for the `-j` parameter to give it a limit on how many jobs it can run at once).

The main reasons behind this are: 
1. It is never good to have more jobs running than cores you have (assuming that, like most laptops, your processor has 4 -8 CPU cores).
2. Passing `-j` on its own seems a little reckless and I don't think that this should be encouraged in pyston's README.
3. In the manual for [GNU make](https://www.gnu.org/software/make/manual/make.html) it says:

   > It is important to be careful when using parallel execution (the `-j` switch; see Parallel Execution) and archives. If multiple `ar` commands run at the same time on the same archive file, they will not know about each other and can corrupt the file.
    > Possibly a future version of make will provide a mechanism to circumvent this problem by serializing all recipes that operate on the same archive file. But for the time being, you must either write your makefiles to avoid this problem in some other way, or not use `-j`.

**Comment by kmod** [comment]
Fair enough! Our build process is quite lengthy so some parallelism is a must, but I just pushed a change to the recommended make command that limits the parallelism to the number of cores.
