### ISSUE TITLE
[Enhancement] - Add a base image on Dockerhub

### ISSUE THREAD

**Issue by sorasful** [pyston/pyston_v2#98]
Hello ! 

Since it seems it's a little bit complicated to setup Pyston, I was thinking it may be a good idea to create a base image so people can start from it, saving the time to set it up correctly.

And it may be useful to upload it on Dockerhub for easier distribution.

What do you think ?

**Comment by undingen** [comment]
Good idea, I also recently learned that it's very easy to execute a linux docker image inside macOS so it would also make it easier for people using apple hardware to use/try out pyston.

**Comment by kmod** [comment]
Hi @sorasful! I just uploaded an image to Dockerhub under pyston:pyston. I don't use docker much myself, would you mind giving it a try?

**Comment by sorasful** [comment]
Hey @kmod , I put a little comment on your commit. But to me that seems cool for testing purposes. For production image, we may need to do some cleanup to have a smaller image !

**Comment by kmod** [comment]
There's stuff that could be improved, but we have the image now! So I'm closing this
